<?php

namespace BotellaBundle\Repository;

/**
* CommentRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsWithArticle($limit)
    {
        $qb = $this->createQueryBuilder('a');
        // On fait une jointure avec l'entité Advert avec pour alias « adv »
        $qb
        ->innerJoin('a.article', 'art')
        ->addSelect('art')
        ;
        // Puis on ne retourne que $limit résultats
        $qb->setMaxResults($limit);
        // Enfin, on retourne le résultat
        return $qb
        ->getQuery()
        ->getResult()
        ;
    }
}
